spring:
  datasource:

    url: jdbc:mysql://autorack.proxy.rlwy.net:21335/railway #mysql://root:BQTkaWtjYojhxiLpYFuGiQwbSCczyTRH@autorack.proxy.rlwy.net:21335/railway
    username: root
    password: BQTkaWtjYojhxiLpYFuGiQwbSCczyTRH

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: "/api"
  port: ${PORT_NUMBER}
